apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "remote-mcp-adapter.configMapName" . }}
  namespace: {{ include "remote-mcp-adapter.namespace" . }}
  labels:
    {{- include "remote-mcp-adapter.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $configValues := .Values.config | default (dict) }}
    {{- $adapterConfig := index $configValues "config.yaml" | default (dict) }}
    {{- tpl (toYaml $adapterConfig) . | nindent 4 }}
