"""Session-scoped artifact resource provider."""

from __future__ import annotations

import asyncio
import logging
from typing import Any

from fastmcp.exceptions import ResourceError, ToolError
from fastmcp.resources import Resource
from fastmcp.server.dependencies import get_context
from fastmcp.server.providers.base import Provider

from ..core.repo.records import ArtifactRecord
from ..core.storage.artifact_access import (
    ArtifactFileMissingError,
    ArtifactFilenameMismatchError,
    ArtifactNotFoundError,
    ArtifactSessionMismatchError,
    ensure_artifact_session_match,
    resolve_artifact_for_read,
)
from ..core.storage.store import SessionStore

logger = logging.getLogger(__name__)


def _artifact_uri(uri_scheme: str, session_id: str, artifact_id: str, filename: str) -> str:
    """Build the canonical artifact URI string from its components.

    Args:
        uri_scheme: URI scheme prefix (e.g. ``artifact://``).
        session_id: Session identifier.
        artifact_id: Artifact identifier.
        filename: Artifact filename.

    Returns:
        Full artifact URI string.
    """
    return f"{uri_scheme}sessions/{session_id}/{artifact_id}/{filename}"


def _raise_resource_error_for_artifact_access(error: Exception) -> None:
    """Map artifact-access domain errors to stable ResourceError messages.

    Args:
        error: Domain exception to translate.

    Raises:
        ResourceError: Translated error with stable user-facing message.
    """
    if isinstance(error, ArtifactSessionMismatchError):
        raise ResourceError("Artifact session mismatch.") from error
    if isinstance(error, ArtifactNotFoundError | ArtifactFilenameMismatchError):
        raise ResourceError("Artifact not found.") from error
    if isinstance(error, ArtifactFileMissingError):
        raise ResourceError("Artifact file missing.") from error
    raise error


class SessionArtifactProvider(Provider):
    """Resource provider that exposes only current-session artifacts."""

    def __init__(
        self,
        *,
        store: SessionStore,
        server_id: str,
        uri_scheme: str,
        enabled: bool,
    ):
        """Initialize the artifact resource provider.

        Args:
            store: Session store for artifact lookups.
            server_id: Server identifier scoping artifact access.
            uri_scheme: URI scheme prefix for artifact URIs.
            enabled: Whether resource exposure is active.
        """
        super().__init__()
        self._store = store
        self._server_id = server_id
        self._uri_scheme = uri_scheme
        self._enabled = enabled

    def _record_to_resource(self, record: ArtifactRecord) -> Resource:
        """Wrap an ArtifactRecord as a session-guarded Resource with lazy file reads.

        Args:
            record: Committed artifact record.

        Returns:
            ``Resource`` with a session-scoped read function.
        """
        uri = _artifact_uri(self._uri_scheme, record.session_id, record.artifact_id, record.filename)

        async def read_fn() -> bytes | str:
            """Read the artifact bytes/text for the current session after staleness check."""
            ctx = get_context()
            try:
                ensure_artifact_session_match(expected_session_id=record.session_id, actual_session_id=ctx.session_id)
            except ArtifactSessionMismatchError as exc:
                _raise_resource_error_for_artifact_access(exc)
            try:
                refreshed = await resolve_artifact_for_read(
                    store=self._store,
                    server_id=self._server_id,
                    session_id=record.session_id,
                    artifact_id=record.artifact_id,
                    expected_filename=record.filename,
                )
            except (ArtifactNotFoundError, ArtifactFileMissingError, ArtifactFilenameMismatchError) as exc:
                _raise_resource_error_for_artifact_access(exc)
            data = await asyncio.to_thread(refreshed.abs_path.read_bytes)
            if refreshed.mime_type.startswith("text/"):
                return data.decode("utf-8", errors="replace")
            return data

        return Resource.from_function(
            fn=read_fn,
            uri=uri,
            name=record.filename,
            description=f"Artifact generated by {record.tool_name or 'adapter'}",
            mime_type=record.mime_type,
            meta={"size_bytes": record.size_bytes},
        )

    async def _list_resources(self) -> list[Resource]:
        """Return all session artifacts that are flagged for resource exposure."""
        if not self._enabled:
            return []
        try:
            session_id = get_context().session_id
        except RuntimeError:
            return []
        records = await self._store.list_artifacts(
            server_id=self._server_id,
            session_id=session_id,
            touch=False,
        )
        return [self._record_to_resource(record) for record in records if record.expose_as_resource]

    async def _get_resource(self, uri: str, version: Any | None = None) -> Resource | None:
        """Resolve an artifact resource by URI, enforcing session scope.

        Args:
            uri: Artifact URI to resolve.
            version: Unused version parameter.

        Returns:
            Matching ``Resource``, or None if not found or not exposed.
        """
        if not self._enabled or not uri.startswith(self._uri_scheme):
            return None
        del version
        try:
            session_id = get_context().session_id
        except RuntimeError:
            return None
        try:
            record = await self._store.resolve_artifact_uri(
                server_id=self._server_id,
                session_id=session_id,
                artifact_uri=uri,
                uri_scheme=self._uri_scheme,
            )
        except (KeyError, ValueError, ToolError):
            return None
        except Exception as exc:
            logger.debug("Failed to resolve artifact resource URI", exc_info=exc)
            return None
        if not record.expose_as_resource:
            return None
        return self._record_to_resource(record)

    async def _list_tools(self) -> list[Any]:
        """No local tools are exposed by this provider."""
        return []
